"""create_alerts_table

Revision ID: 1da248ebf9b0
Revises: c5e423d1728e
Create Date: 2026-09-28 15:48:21.107548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da248ebf9b0'
down_revision: Union[str, Sequence[str], None] = 'c5e423d1728e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thermal_event_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('NEW_THERMAL_ANOMALY', 'INDUSTRIAL_HEAT_SOURCE_ALERT', 'PERSISTENT_THERMAL_ACTIVITY', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('model_probability', sa.Float(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thermal_event_id'], ['thermal_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_thermal_event_id'), 'alerts', ['thermal_event_id'], unique=False)
    op.drop_index(op.f('idx_classifications_event_id'), table_name='classifications')
    op.create_index(op.f('ix_classifications_predicted_class'), 'classifications', ['predicted_class'], unique=False)
    op.create_index(op.f('ix_classifications_thermal_event_id'), 'classifications', ['thermal_event_id'], unique=False)
    op.drop_constraint(op.f('event_features_thermal_event_id_key'), 'event_features', type_='unique')
    op.drop_index(op.f('idx_features_event_id'), table_name='event_features')
    op.create_index('idx_features_event_id', 'event_features', ['thermal_event_id'], unique=False)
    op.create_index(op.f('ix_event_features_thermal_event_id'), 'event_features', ['thermal_event_id'], unique=True)
    op.drop_index(op.f('idx_industrial_facilities_name'), table_name='industrial_facilities')
    op.create_index(op.f('ix_industrial_facilities_facility_type'), 'industrial_facilities', ['facility_type'], unique=False)
    op.create_index(op.f('ix_industrial_facilities_name'), 'industrial_facilities', ['name'], unique=False)
    op.create_index(op.f('ix_industrial_facilities_source_id'), 'industrial_facilities', ['source_id'], unique=False)
    op.drop_index(op.f('idx_risk_event_id'), table_name='risk_assessments')
    op.create_index(op.f('ix_risk_assessments_risk_level'), 'risk_assessments', ['risk_level'], unique=False)
    op.create_index(op.f('ix_risk_assessments_risk_score'), 'risk_assessments', ['risk_score'], unique=False)
    op.create_index(op.f('ix_risk_assessments_thermal_event_id'), 'risk_assessments', ['thermal_event_id'], unique=False)
    op.drop_index(op.f('idx_sat_obs_event_id'), table_name='satellite_observations')
    op.drop_index(op.f('idx_sat_obs_product_id'), table_name='satellite_observations')
    op.create_index(op.f('ix_satellite_observations_acquisition_time'), 'satellite_observations', ['acquisition_time'], unique=False)
    op.create_index(op.f('ix_satellite_observations_product_id'), 'satellite_observations', ['product_id'], unique=False)
    op.create_index(op.f('ix_satellite_observations_satellite'), 'satellite_observations', ['satellite'], unique=False)
    op.create_index(op.f('ix_satellite_observations_thermal_event_id'), 'satellite_observations', ['thermal_event_id'], unique=False)
    op.drop_index(op.f('idx_assoc_facility_id'), table_name='thermal_event_facility_associations')
    op.drop_index(op.f('idx_assoc_thermal_event_id'), table_name='thermal_event_facility_associations')
    op.create_index(op.f('ix_thermal_event_facility_associations_distance_meters'), 'thermal_event_facility_associations', ['distance_meters'], unique=False)
    op.create_index(op.f('ix_thermal_event_facility_associations_facility_id'), 'thermal_event_facility_associations', ['facility_id'], unique=False)
    op.create_index(op.f('ix_thermal_event_facility_associations_thermal_event_id'), 'thermal_event_facility_associations', ['thermal_event_id'], unique=False)
    op.drop_index(op.f('idx_thermal_events_source_event_id'), table_name='thermal_events')
    op.create_index(op.f('ix_thermal_events_detected_at'), 'thermal_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_thermal_events_source_event_id'), 'thermal_events', ['source_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thermal_events_source_event_id'), table_name='thermal_events')
    op.drop_index(op.f('ix_thermal_events_detected_at'), table_name='thermal_events')
    op.create_index(op.f('idx_thermal_events_source_event_id'), 'thermal_events', ['source_event_id'], unique=False)
    op.drop_index(op.f('ix_thermal_event_facility_associations_thermal_event_id'), table_name='thermal_event_facility_associations')
    op.drop_index(op.f('ix_thermal_event_facility_associations_facility_id'), table_name='thermal_event_facility_associations')
    op.drop_index(op.f('ix_thermal_event_facility_associations_distance_meters'), table_name='thermal_event_facility_associations')
    op.create_index(op.f('idx_assoc_thermal_event_id'), 'thermal_event_facility_associations', ['thermal_event_id'], unique=False)
    op.create_index(op.f('idx_assoc_facility_id'), 'thermal_event_facility_associations', ['facility_id'], unique=False)
    op.drop_index(op.f('ix_satellite_observations_thermal_event_id'), table_name='satellite_observations')
    op.drop_index(op.f('ix_satellite_observations_satellite'), table_name='satellite_observations')
    op.drop_index(op.f('ix_satellite_observations_product_id'), table_name='satellite_observations')
    op.drop_index(op.f('ix_satellite_observations_acquisition_time'), table_name='satellite_observations')
    op.create_index(op.f('idx_sat_obs_product_id'), 'satellite_observations', ['product_id'], unique=False)
    op.create_index(op.f('idx_sat_obs_event_id'), 'satellite_observations', ['thermal_event_id'], unique=False)
    op.drop_index(op.f('ix_risk_assessments_thermal_event_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_risk_score'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_risk_level'), table_name='risk_assessments')
    op.create_index(op.f('idx_risk_event_id'), 'risk_assessments', ['thermal_event_id'], unique=False)
    op.drop_index(op.f('ix_industrial_facilities_source_id'), table_name='industrial_facilities')
    op.drop_index(op.f('ix_industrial_facilities_name'), table_name='industrial_facilities')
    op.drop_index(op.f('ix_industrial_facilities_facility_type'), table_name='industrial_facilities')
    op.create_index(op.f('idx_industrial_facilities_name'), 'industrial_facilities', ['name'], unique=False)
    op.drop_index(op.f('ix_event_features_thermal_event_id'), table_name='event_features')
    op.drop_index('idx_features_event_id', table_name='event_features')
    op.create_index(op.f('idx_features_event_id'), 'event_features', ['thermal_event_id'], unique=True)
    op.create_unique_constraint(op.f('event_features_thermal_event_id_key'), 'event_features', ['thermal_event_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_classifications_thermal_event_id'), table_name='classifications')
    op.drop_index(op.f('ix_classifications_predicted_class'), table_name='classifications')
    op.create_index(op.f('idx_classifications_event_id'), 'classifications', ['thermal_event_id'], unique=False)
    op.drop_index(op.f('ix_alerts_thermal_event_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
