"""Add notification tracking to alerts

Revision ID: 63775e48fefa
Revises: 1da248ebf9b0
Create Date: 2026-09-30 23:42:11.654962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63775e48fefa'
down_revision: Union[str, Sequence[str], None] = '1da248ebf9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    notification_status_enum = sa.Enum('PENDING', 'SENT', 'FAILED', 'DISABLED', 'NOT_APPLICABLE', name='notificationstatus')
    notification_status_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('alerts', sa.Column('notification_status', notification_status_enum, nullable=False, server_default='NOT_APPLICABLE'))
    op.add_column('alerts', sa.Column('notification_timestamp', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('notification_recipient', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('notification_error', sa.String(), nullable=True))
    op.create_index(op.f('ix_alerts_notification_status'), 'alerts', ['notification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_notification_status'), table_name='alerts')
    op.drop_column('alerts', 'notification_error')
    op.drop_column('alerts', 'notification_recipient')
    op.drop_column('alerts', 'notification_timestamp')
    op.drop_column('alerts', 'notification_status')
    
    notification_status_enum = sa.Enum('PENDING', 'SENT', 'FAILED', 'DISABLED', 'NOT_APPLICABLE', name='notificationstatus')
    notification_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
